# Generated by Django 5.0.6 on 2024-05-27 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file_field', models.FileField(upload_to='Texts/uploaded')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('text_type', models.CharField(choices=[('Q', 'Questioned'), ('K', 'Known'), ('R', 'Reference')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='FreqWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=255)),
                ('count', models.IntegerField()),
                ('relate_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frequent_words', to='app_analysis.filemodel')),
            ],
        ),
        migrations.CreateModel(
            name='SelectedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(default=None, max_length=255, null=True)),
                ('files', models.ManyToManyField(to='app_analysis.filemodel')),
            ],
        ),
    ]
