# Generated by Django 5.0.6 on 2024-05-16 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_analysis', '0002_filemodel_text_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filemodel',
            name='text_type',
            field=models.CharField(choices=[('Q', 'Questioned'), ('K', 'Known'), ('R', 'Reference')], max_length=10),
        ),
    ]
