# Generated by Django 5.0.4 on 2024-05-16 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_analysis', '0003_alter_filemodel_file_field'),
        ('app_analysis', '0003_alter_filemodel_text_type'),
    ]

    operations = [
    ]
